### ISSUE TITLE
Could not pass event PlayerJoinEvent

### ISSUE THREAD

**Issue by NathanNr** [NathanNr/AntiLaby#5]
Error:

17:40:59 [ERROR] Could not pass event PlayerJoinEvent to AntiLaby v1.8.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigo
t-3fb9445-2b6c9f4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-
3fb9445-2b6c9f4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigo
t-3fb9445-2b6c9f4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:121) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:115) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:74) [ProtocolSupport.jar:?]
        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.F_(SpigotLoginListenerPlay.java:67) [ProtocolSupport.jar:?]
        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.Error: Unresolved compilation problems:
        PacketDataSerializer cannot be resolved to a type
        PacketDataSerializer cannot be resolved to a type
        PacketPlayOutCustomPayload cannot be resolved to a type
        PacketPlayOutCustomPayload cannot be resolved to a type
        CraftPlayer cannot be resolved to a type
        CraftPlayer cannot be resolved to a type

 at com.github.nathannr.antilaby.nms.Nms_v1_11_R1.setLabyModFeature(Nms_v1_11_R1.java:29) ~[?:?]
        at com.github.nathannr.antilaby.api.antilabypackages.AntiLabyPackager.sendPackages(AntiLabyPackager.java:99) ~[?:?]
        at com.github.nathannr.antilaby.main.events.PlayerJoin.onPlayerJoin(PlayerJoin.java:18) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
        ... 16 more

https://hastebin.com/irehamonin.vbs
Bug report by [Ac3dUd3](https://www.spigotmc.org/members/80704/)

**Comment by NathanNr** [comment]
Fixed in [1.8.2-pre1](https://github.com/NathanNr/AntiLaby/releases/tag/1.8.2-pre1).
